### ISSUE TITLE
I could use some help setting this up (this isnt an issue)

### ISSUE THREAD

**Issue by Adamsmashem** [DebitCardz/minehut-deployment#1]
This seems to be the best way to contact you so sorry of this isnt the right place. Im somewhat new to github and im no sure how a completed `.deployment_information` should look. Can you give me an example  of how it should be?

Also, how do I use this to run a custom server jar on my minehut server (if its possilbe)?

Thanks!

**Comment by DebitCardz** [comment]
Hey, thanks for using my software.
I personally would not recommend using this in a production server since it does some pretty hacky things to get everything to work however, if you really want to here's how you do it.

Make a `.deployment_information` file with only this value
```
jar_name={JAR NAME}
```
Replace `{JAR NAME}` with the name of your new jar, place it in your main directory where your other `server.jar` file is but make sure to rename it and you should be fine.

**Comment by Adamsmashem** [comment]
Hey, thanks so much for the help! Im trying to run a velocity server without buying a server plan. If I didnt want things to be hacky ill just buy a plan instead so im fine with that. 
I tried doing what you said and I put in` jar_name=server2.jar` (do I need quotes?) server2.jar is paper 1.19.4 right now (just to test)
But nothing has changed, and I dont see the plugin in my plugin list. Im using a paper 1.17.1 with bukkit-0.0.1-all.jar istalled. Any tips? (im fine with changing server versoins from 1.17.1 if I need to)

**Comment by Adamsmashem** [comment]
Never mind! I changed the minehut server versoin to 1.19.3 and its working! Velocity is too!

This is great man, good job on somehow doing this. Ill let you know if I have anymore problems.

**Comment by Adamsmashem** [comment]
Im having trouble acually joining my velocity server, I think this error is from the minehut proxy trying to connect me to my velocity server, as it never shows me trying to join on the velocity console. Im not too familar with how proxy to proxy connections work, and this isnt exactly related to this plugin, but do you think you can help me with this? 
Thanks!
![image](https://user-images.githubusercontent.com/68350584/230534430-ad2f4167-dcdf-4fd1-853f-8f68188680bc.png)

**Comment by DebitCardz** [comment]
My apologies for the delayed response.
Have you properly setup your velocity/paper configurations?

In velocity set your forwarding mode to `MODERN`, on your Spigot servers also enable Velocity support.
You also need to add the server to the list of servers in your `velocity.toml` file.

**Comment by Adamsmashem** [comment]
No problem! Im sure I set up my velocity server correctly as Ive tested it on my own device and everything works. Forwarding is modern and the spigot server is already set up properly. The problem is that when you buy a server plan and choose velocity, minehut will configure it to connect to their servers, but when doing it using this plugin, minehut wont connect to my server. Nothing shows up in console after I join, and I get the same error even when using bugeecoord or waterfall. 
I even bought a daily plan, and used velocity officially, and everthing worked. Then, I used this method with the same config and files from the official velocity versoin, but the same problem.

Heres my velocity.tmol: (coverted to .txt)
[velocity.toml.txt](https://github.com/DebitCardz/minehut-deployment/files/11181365/velocity.toml.txt)

This might be a minehut thing that I cannot fix with access to the minehut proxy servers, but I hope there is a way.

Heres my minehut console, copied after trying to join: (nothing new shows up in the spigot backend server when I join)
The minehut version is paper 1.19.3, but running the latest velocity versoin. 
```
Server starting, setting up fifo connections and writing server ready.
Downloading mojang_1.19.3.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12) Host: Linux 5.15.0-46-generic (amd64)
Loading libraries, please wait...
2023-04-07 20:29:05,994 ServerMain WARN Advanced terminal features are not available in this environment
[20:29:06 ERROR]: [io.papermc.paper.plugin.provider.source.DirectoryProviderSource] Error loading plugin: Directory 'plugins/velocity-0.0.1-all.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/velocity-0.0.1-all.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.19.3.jar:git-Paper-431]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$2(DirectoryProviderSource.java:32) ~[paper-1.19.3.jar:git-Paper-431]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:30) ~[paper-1.19.3.jar:git-Paper-431]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.19.3.jar:git-Paper-431]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.19.3.jar:git-Paper-431]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.Main.main(Main.java:114) ~[paper-1.19.3.jar:git-Paper-431]
	at org.bukkit.craftbukkit.Main.main(Main.java:302) ~[paper-1.19.3.jar:git-Paper-431]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/velocity-0.0.1-all.jar' is not a valid plugin file, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:54) ~[paper-1.19.3.jar:git-Paper-431]
	... 20 more
[20:29:09 INFO]: Building unoptimized datafixer
[20:29:11 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:29:12 INFO]: Loaded 7 recipes
[20:29:13 INFO]: Starting minecraft server version 1.19.3
[20:29:13 INFO]: Loading properties
[20:29:13 INFO]: This server is running Paper version git-Paper-431 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e574412)
[20:29:13 INFO]: Server Ping Player Sample Count: 12
[20:29:13 INFO]: Using 4 threads for Netty based IO
[20:29:13 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[20:29:13 INFO]: Default game type: SURVIVAL
[20:29:13 INFO]: Generating keypair
[20:29:14 INFO]: Starting Minecraft server on *:25575
[20:29:14 INFO]: Using epoll channel type
[20:29:14 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[20:29:14 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[20:29:14 INFO]: [com.minehut.minehutplugin.net.mapper.ProtocolMapper] Found matching server revision v1_19_R2 (V1_19_R2)
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[20:29:16 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-6a125bd0-b247)...
[20:29:16 INFO]: Loading localizations...
[20:29:16 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[20:29:16 INFO]: Loading plugins...
[20:29:16 ERROR]: Unable to load plugin plugins/bukkit-0.0.1-all (1).jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file bukkit-0.0.1-all (1).jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
[20:29:16 ERROR]: Unable to load plugin plugins/MinehutCosmetics.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file MinehutCosmetics.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
[20:29:16 ERROR]: Unable to load plugin plugins/MinehutAnalytics.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file MinehutAnalytics.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server2.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
[20:29:16 INFO]: Deployed from Github.
[20:29:16 INFO]: Loaded plugin mh-deployment-velocity 0.0.1 by Tech
[20:29:16 INFO]: Loaded plugin viaversion 4.6.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[20:29:16 INFO]: Loaded 2 plugins
[20:29:17 INFO] [viaversion]: Loading block connection mappings ...
[20:29:17 INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[20:29:17 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:29:17 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:29:17 INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[20:29:17 INFO] [viaversion]: Highest supported version by the proxy: 1.19.4 (762)
[20:29:17 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25575
[20:29:17 INFO]: Done (1.53s)!
[20:29:17 INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
```

**Comment by DebitCardz** [comment]
Haha are you trying to use my plugin to turn your server into a velocity server? That's pretty funny.
I believe Minehut does special networking for Velocity since they basically have to do this.
`MH Proxy -> Proxy -> Spigot`, I'm not too sure how to resolve this issue unfortunately but I don't think my plugin will be able to help you with this.

You should probably just buy the Minehut plan to allow for external servers, it'd be much easier.

**Comment by Adamsmashem** [comment]
Thats unfortunate, but thanks for the help and making this! I will definitely use this for some other server in the future.

Another question, is it possible to keep a free server up 24/7 with this? Or maybe even increase the player limit?

**Comment by DebitCardz** [comment]
Unfortunately not as that would be breaking Minehut TOS.

**Comment by Adamsmashem** [comment]
Yes I know that would be breaking TOS, but for science I would like to know ;)
(or did you intentionally make that impossible?)

Also running a proxy server without a server plan is prob agaisnt it too, hell maybe even using this in the first place isnt allowed.

**Comment by DebitCardz** [comment]
I didn't intentionally make it impossible but I never implemented such functionality nor do I plan to do such.

Also this plugin does not break Minehut TOS, I've ran it by multiple administrators however, with your use case it may break TOS 🤷‍♀️
You can modify the code however you want though I don't mind.
